favicon: https://d33wubrfki0l68.cloudfront.net/6657ba50e702d84afb32fe846bed54fba1a77add/827ae/logo.svg
avatar: https://d33wubrfki0l68.cloudfront.net/6657ba50e702d84afb32fe846bed54fba1a77add/827ae/logo.svg
katex: false
force_https: true
check_update: true

menus:
  - name: 首页
    link: /
  - name: 归档
    link: /archives/
  - name: 标签
    link: /tags/
  - name: 友链
    link: /friends/
post:
  feature: true
disqus:
  enable: false
  shortname: 'Your shortname here'
  api: 'Your api here'
  apikey: 'Your api key here'
  admin: 'Your disqus username here'
gitalk:
  enable: false
  clientId: 'Your Client Id here'
  clientSecret: 'Your Client Secret here'
  repository: 'Your Comment Repository here'
  owner: 'Your github username here'
valine:
  enable: false
  appId: 'Your appID here'
  appKey: 'Your appKey here'
  placeholder: 'Your placeholder here'
  pageSize: 10
web_analytics:
  enable: false
  google: UA-12345678-1
  baidu: 12345678
footer: |
  Footer HTML
friends:
  - name: 宝硕博客
    link: https://blog.baoshuo.ren/
    logo: https://cdn.jsdelivr.net/npm/bsi@0.0.2/favicon/128x128.png
    description: 学习，就是发现自己越来越菜的过程。
